name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install nix
      uses: cachix/install-nix-action@v6

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: labextension/node_modules
        key: ${{ runner.OS }}-node

    - name: Install
      run: |
        nix-shell --run "make dev-install"

    - name: Run linters
      run: |
        nix-shell --run "make lint"

    - name: Run tests
      run: |
        nix-shell --run "make test"

